package try_catch;

public class ex8_8 {

	public static void main(String[] args) {
		// unchecked 예외 :예외처리를 하지 않았음에도 성공적으로 컴파일 됨. RuntimeException클래스와 그 자손들은 예외처리를 강제하지 않음.
		
		throw new RuntimeException(); // 고의로 발생
		

	}

}
